import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-10, 10, 200)
plt.figure('Графики', figsize=(20, 20))
plt.subplot(2, 2, 2)
plt.plot(x, np.sin(x))
plt.title("Зависимость: y = sin(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.subplot(2, 2, 1)
plt.plot(x, np.cos(x))
plt.title("Зависимость: y = cos(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.subplot(2, 2, 3)
plt.plot(x, x ** 2)
plt.title("Зависимость: y = x ^ 2")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.subplot(2, 2, 4)
x1 = np.linspace(-10, -0.01, 100)
plt.plot(x1, 2 / x1, color='r')
x2 = np.linspace(0.01, 10, 100)
plt.plot(x2, 2 / x2, color='r')
plt.title("Зависимость: y = 2 / x")
plt.xlabel("x")
plt.ylabel("y")
plt.grid()
plt.show()
